name: FlameCore
version: '1.1.3'
main: dream.soulflame.flamecore.FlameCore
authors: [ SoulFlame ]
depend:
  - PlaceholderAPI
  - PlayerPoints
  - Vault
softdepend:
  - DragonCore
commands:
  flamecore:
    aliases:
      - fc
