#模块启用设置
Module:
  #是否启用 [true 是|false 否]
  Enable: true

#两种检测
# name 检测生物名称[包含即可]
# entity 检测原版生物实体类型
Entities:
  - 'name<->超级boss'
  - 'entity<->ZOMBIE'
#打开后每次攻击生物
#将会输出对应的原版生物名
Debug: false

#语言设置
Message:
  #debug信息
  DebugInfo:
    - '[message]&b你攻击的实体类型是&f: &e<entity>'