#模块启用设置
Module:
  #是否启用 [true 是|false 否]
  Enable: true

#检测的物品列表
# 三种检测
# lore lore词条
# name 物品名称
# material 物品英文材质
#只要包含<->后的文字就无法攻击
CheckList:
  - 'lore<->已经不能使用了'
  - 'name<->残破大剑'
  - 'material<->SWORD'