#模块启用设置
Module:
  #是否启用 [true 是|false 否]
  Enable: false

#消息设置
Message:
  #获取玩家槽位时发送的消息
  GetSlotItem:
    - '[message]&a你成功获取了 &b<target> &a的&r <item> &7* &d<amount>'
  #设置玩家槽位时发送的消息
  SetSlotItem:
    - '[message]&a你成功将手上的物品放入了 &b<target> &a的 &e<slot> &a中'
  #交换玩家的两个槽位时发送的消息
  ChangeSlotItem:
    - '[message]&a你成功将 &b<target> &a的 &b<preSlot> &a与 &3<newSlot> &a交换'
  #槽位里没有物品时发送的消息
  SlotIsNull:
    - '[message]&c该槽位没有物品, 无法执行该操作'